---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-less
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "while true; do echo $(hostname) 'is alive at ' && date ; sleep 5; done" ]
    args:
    - sleep
    - "1000"
    
    
    ## create namespace 
    ## kubectl apply -f  k8s_test_deployment.yml
